
use pjsip_sys::*;
use super::utils::AutoCreate;


impl AutoCreate<pjsip_cfg_t> for pjsip_cfg_t {}
impl AutoCreate<pjsip_cfg_t__bindgen_ty_1> for pjsip_cfg_t__bindgen_ty_1 {}
impl AutoCreate<pjsip_cfg_t__bindgen_ty_2> for pjsip_cfg_t__bindgen_ty_2 {}
impl AutoCreate<pjsip_cfg_t__bindgen_ty_3> for pjsip_cfg_t__bindgen_ty_3 {}
impl AutoCreate<pjsip_cfg_t__bindgen_ty_4> for pjsip_cfg_t__bindgen_ty_4 {}
impl AutoCreate<pjsip_cfg_t__bindgen_ty_5> for pjsip_cfg_t__bindgen_ty_5 {}
impl AutoCreate<pjsip_tpmgr> for pjsip_tpmgr {}
impl AutoCreate<pjsip_endpoint> for pjsip_endpoint {}
impl AutoCreate<pjsip_resolver_t> for pjsip_resolver_t {}
impl AutoCreate<pjsip_buffer> for pjsip_buffer {}
impl AutoCreate<pjsip_host_port> for pjsip_host_port {}
impl AutoCreate<pjsip_host_info> for pjsip_host_info {}
impl AutoCreate<pjsip_param> for pjsip_param {}
impl AutoCreate<pjsip_uri_vptr> for pjsip_uri_vptr {}
impl AutoCreate<pjsip_uri> for pjsip_uri {}
impl AutoCreate<pjsip_sip_uri> for pjsip_sip_uri {}
impl AutoCreate<pjsip_name_addr> for pjsip_name_addr {}
impl AutoCreate<pjsip_other_uri> for pjsip_other_uri {}
impl AutoCreate<pjsip_tel_uri> for pjsip_tel_uri {}
impl AutoCreate<pjsip_method> for pjsip_method {}
impl AutoCreate<pjsip_hdr_vptr> for pjsip_hdr_vptr {}
impl AutoCreate<pjsip_hdr> for pjsip_hdr {}
impl AutoCreate<pjsip_request_line> for pjsip_request_line {}
impl AutoCreate<pjsip_status_line> for pjsip_status_line {}
impl AutoCreate<pjsip_media_type> for pjsip_media_type {}
impl AutoCreate<pjsip_msg_body> for pjsip_msg_body {}
impl AutoCreate<pjsip_msg> for pjsip_msg {}
impl AutoCreate<pjsip_msg__bindgen_ty_1> for pjsip_msg__bindgen_ty_1 {}
impl AutoCreate<pjsip_generic_string_hdr> for pjsip_generic_string_hdr {}
impl AutoCreate<pjsip_generic_int_hdr> for pjsip_generic_int_hdr {}
impl AutoCreate<pjsip_generic_array_hdr> for pjsip_generic_array_hdr {}
impl AutoCreate<pjsip_cid_hdr> for pjsip_cid_hdr {}
impl AutoCreate<pjsip_clen_hdr> for pjsip_clen_hdr {}
impl AutoCreate<pjsip_cseq_hdr> for pjsip_cseq_hdr {}
impl AutoCreate<pjsip_contact_hdr> for pjsip_contact_hdr {}
impl AutoCreate<pjsip_ctype_hdr> for pjsip_ctype_hdr {}
impl AutoCreate<pjsip_fromto_hdr> for pjsip_fromto_hdr {}
impl AutoCreate<pjsip_routing_hdr> for pjsip_routing_hdr {}
impl AutoCreate<pjsip_retry_after_hdr> for pjsip_retry_after_hdr {}
impl AutoCreate<pjsip_via_hdr> for pjsip_via_hdr {}
impl AutoCreate<pjsip_multipart_part> for pjsip_multipart_part {}
impl AutoCreate<pjsip_parser_err_report> for pjsip_parser_err_report {}
impl AutoCreate<pjsip_parse_ctx> for pjsip_parse_ctx {}
impl AutoCreate<pjsip_parser_const_t> for pjsip_parser_const_t {}
impl AutoCreate<pjsip_event> for pjsip_event {}
impl AutoCreate<pjsip_event__bindgen_ty_1> for pjsip_event__bindgen_ty_1 {}
impl AutoCreate<pjsip_event__bindgen_ty_1__bindgen_ty_1> for pjsip_event__bindgen_ty_1__bindgen_ty_1 {}
impl AutoCreate<pjsip_event__bindgen_ty_1__bindgen_ty_2> for pjsip_event__bindgen_ty_1__bindgen_ty_2 {}
impl AutoCreate<pjsip_event__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1> for pjsip_event__bindgen_ty_1__bindgen_ty_2__bindgen_ty_1 {}
impl AutoCreate<pjsip_event__bindgen_ty_1__bindgen_ty_3> for pjsip_event__bindgen_ty_1__bindgen_ty_3 {}
impl AutoCreate<pjsip_event__bindgen_ty_1__bindgen_ty_4> for pjsip_event__bindgen_ty_1__bindgen_ty_4 {}
impl AutoCreate<pjsip_event__bindgen_ty_1__bindgen_ty_5> for pjsip_event__bindgen_ty_1__bindgen_ty_5 {}
impl AutoCreate<pjsip_event__bindgen_ty_1__bindgen_ty_6> for pjsip_event__bindgen_ty_1__bindgen_ty_6 {}
impl AutoCreate<pjsip_module> for pjsip_module {}
impl AutoCreate<pjsip_server_addresses> for pjsip_server_addresses {}
impl AutoCreate<pjsip_server_addresses__bindgen_ty_1> for pjsip_server_addresses__bindgen_ty_1 {}
impl AutoCreate<pjsip_ext_resolver> for pjsip_ext_resolver {}
impl AutoCreate<pjsip_tpselector> for pjsip_tpselector {}
impl AutoCreate<pjsip_rx_data_op_key> for pjsip_rx_data_op_key {}
impl AutoCreate<pjsip_rx_data> for pjsip_rx_data {}
impl AutoCreate<pjsip_rx_data__bindgen_ty_1> for pjsip_rx_data__bindgen_ty_1 {}
impl AutoCreate<pjsip_rx_data__bindgen_ty_2> for pjsip_rx_data__bindgen_ty_2 {}
impl AutoCreate<pjsip_rx_data__bindgen_ty_3> for pjsip_rx_data__bindgen_ty_3 {}
impl AutoCreate<pjsip_rx_data__bindgen_ty_4> for pjsip_rx_data__bindgen_ty_4 {}
impl AutoCreate<pjsip_tx_data_op_key> for pjsip_tx_data_op_key {}
impl AutoCreate<pjsip_tx_data> for pjsip_tx_data {}
impl AutoCreate<pjsip_tx_data__bindgen_ty_1> for pjsip_tx_data__bindgen_ty_1 {}
impl AutoCreate<pjsip_tx_data__bindgen_ty_2> for pjsip_tx_data__bindgen_ty_2 {}
impl AutoCreate<pjsip_transport_key> for pjsip_transport_key {}
impl AutoCreate<pjsip_transport> for pjsip_transport {}
impl AutoCreate<pjsip_tpfactory> for pjsip_tpfactory {}
impl AutoCreate<pjsip_tpmgr_fla2_param> for pjsip_tpmgr_fla2_param {}
impl AutoCreate<pjsip_transport_state_info> for pjsip_transport_state_info {}
impl AutoCreate<pjsip_tp_dropped_data> for pjsip_tp_dropped_data {}
impl AutoCreate<pjsip_process_rdata_param> for pjsip_process_rdata_param {}
impl AutoCreate<pjsip_target> for pjsip_target {}
impl AutoCreate<pjsip_target_set> for pjsip_target_set {}
impl AutoCreate<pjsip_send_state> for pjsip_send_state {}
impl AutoCreate<pjsip_response_addr> for pjsip_response_addr {}
impl AutoCreate<pjsip_udp_transport_cfg> for pjsip_udp_transport_cfg {}
impl AutoCreate<pjsip_tcp_transport_cfg> for pjsip_tcp_transport_cfg {}
impl AutoCreate<pjsip_tls_on_accept_fail_param> for pjsip_tls_on_accept_fail_param {}
impl AutoCreate<pjsip_tls_setting> for pjsip_tls_setting {}
impl AutoCreate<pjsip_tls_state_info> for pjsip_tls_state_info {}
impl AutoCreate<pjsip_common_credential> for pjsip_common_credential {}
impl AutoCreate<pjsip_digest_credential> for pjsip_digest_credential {}
impl AutoCreate<pjsip_pgp_credential> for pjsip_pgp_credential {}
impl AutoCreate<pjsip_oauth_credential> for pjsip_oauth_credential {}
impl AutoCreate<pjsip_authorization_hdr> for pjsip_authorization_hdr {}
impl AutoCreate<pjsip_authorization_hdr__bindgen_ty_1> for pjsip_authorization_hdr__bindgen_ty_1 {}
impl AutoCreate<pjsip_common_challenge> for pjsip_common_challenge {}
impl AutoCreate<pjsip_digest_challenge> for pjsip_digest_challenge {}
impl AutoCreate<pjsip_pgp_challenge> for pjsip_pgp_challenge {}
impl AutoCreate<pjsip_www_authenticate_hdr> for pjsip_www_authenticate_hdr {}
impl AutoCreate<pjsip_www_authenticate_hdr__bindgen_ty_1> for pjsip_www_authenticate_hdr__bindgen_ty_1 {}
impl AutoCreate<pjsip_cred_info> for pjsip_cred_info {}
impl AutoCreate<pjsip_cred_info__bindgen_ty_1> for pjsip_cred_info__bindgen_ty_1 {}
impl AutoCreate<pjsip_cred_info__bindgen_ty_1__bindgen_ty_1> for pjsip_cred_info__bindgen_ty_1__bindgen_ty_1 {}
impl AutoCreate<pjsip_cached_auth_hdr> for pjsip_cached_auth_hdr {}
impl AutoCreate<pjsip_cached_auth> for pjsip_cached_auth {}
impl AutoCreate<pjsip_auth_clt_pref> for pjsip_auth_clt_pref {}
impl AutoCreate<pjsip_auth_clt_sess> for pjsip_auth_clt_sess {}
impl AutoCreate<pjsip_auth_lookup_cred_param> for pjsip_auth_lookup_cred_param {}
impl AutoCreate<pjsip_auth_srv> for pjsip_auth_srv {}
impl AutoCreate<pjsip_auth_srv_init_param> for pjsip_auth_srv_init_param {}
impl AutoCreate<pjsip_transaction> for pjsip_transaction {}
impl AutoCreate<pjsip_ua_init_param> for pjsip_ua_init_param {}
impl AutoCreate<pjsip_dlg_party> for pjsip_dlg_party {}
impl AutoCreate<pjsip_dialog> for pjsip_dialog {}
impl AutoCreate<pjsip_dlg_create_uac_param> for pjsip_dlg_create_uac_param {}