
use super::utils::AutoCreate;
use super::*;

impl AutoCreate<pjsua_srv_pres> for pjsua_srv_pres {}
impl AutoCreate<pjsua_logging_config> for pjsua_logging_config {}
impl AutoCreate<pjsua_mwi_info> for pjsua_mwi_info {}
impl AutoCreate<pjsua_reg_info> for pjsua_reg_info {}
impl AutoCreate<pjsua_stream_info> for pjsua_stream_info {}
impl AutoCreate<pjsua_stream_info__bindgen_ty_1> for pjsua_stream_info__bindgen_ty_1 {}
impl AutoCreate<pjsua_stream_stat> for pjsua_stream_stat {}
impl AutoCreate<pjsua_on_stream_precreate_param> for pjsua_on_stream_precreate_param {}
impl AutoCreate<pjsua_on_stream_created_param> for pjsua_on_stream_created_param {}
impl AutoCreate<pjsua_med_tp_state_info> for pjsua_med_tp_state_info {}
impl AutoCreate<pjsua_srtp_opt> for pjsua_srtp_opt {}
impl AutoCreate<pjsua_ip_change_op_info> for pjsua_ip_change_op_info {}
impl AutoCreate<pjsua_ip_change_op_info__bindgen_ty_1> for pjsua_ip_change_op_info__bindgen_ty_1 {}
impl AutoCreate<pjsua_ip_change_op_info__bindgen_ty_2> for pjsua_ip_change_op_info__bindgen_ty_2 {}
impl AutoCreate<pjsua_ip_change_op_info__bindgen_ty_3> for pjsua_ip_change_op_info__bindgen_ty_3 {}
impl AutoCreate<pjsua_ip_change_op_info__bindgen_ty_4> for pjsua_ip_change_op_info__bindgen_ty_4 {}
impl AutoCreate<pjsua_ip_change_op_info__bindgen_ty_5> for pjsua_ip_change_op_info__bindgen_ty_5 {}
impl AutoCreate<pjsua_dtmf_info> for pjsua_dtmf_info {}
impl AutoCreate<pjsua_dtmf_event> for pjsua_dtmf_event {}
impl AutoCreate<pjsua_call_setting> for pjsua_call_setting {}
impl AutoCreate<pjsua_callback> for pjsua_callback {}
impl AutoCreate<pjsua_config> for pjsua_config {}
impl AutoCreate<pjsua_msg_data> for pjsua_msg_data {}
impl AutoCreate<pj_stun_resolve_result> for pj_stun_resolve_result {}
impl AutoCreate<pjsua_ip_change_param> for pjsua_ip_change_param {}
impl AutoCreate<pjsua_ip_change_acc_cfg> for pjsua_ip_change_acc_cfg {}
impl AutoCreate<pjsua_transport_config> for pjsua_transport_config {}
impl AutoCreate<pjsua_transport_info> for pjsua_transport_info {}
impl AutoCreate<pjsua_ice_config> for pjsua_ice_config {}
impl AutoCreate<pjsua_turn_config> for pjsua_turn_config {}
impl AutoCreate<pjsua_acc_config> for pjsua_acc_config {}
impl AutoCreate<pjsua_acc_info> for pjsua_acc_info {}
impl AutoCreate<pjsua_call_media_info> for pjsua_call_media_info {}
impl AutoCreate<pjsua_call_media_info__bindgen_ty_1> for pjsua_call_media_info__bindgen_ty_1 {}
impl AutoCreate<pjsua_call_media_info__bindgen_ty_1__bindgen_ty_1> for pjsua_call_media_info__bindgen_ty_1__bindgen_ty_1 {}
impl AutoCreate<pjsua_call_media_info__bindgen_ty_1__bindgen_ty_2> for pjsua_call_media_info__bindgen_ty_1__bindgen_ty_2 {}
impl AutoCreate<pjsua_call_info> for pjsua_call_info {}
impl AutoCreate<pjsua_call_info__bindgen_ty_1> for pjsua_call_info__bindgen_ty_1 {}
impl AutoCreate<pjsua_call_vid_strm_op_param> for pjsua_call_vid_strm_op_param {}
impl AutoCreate<pjsua_call_send_dtmf_param> for pjsua_call_send_dtmf_param {}
impl AutoCreate<pjsua_buddy_config> for pjsua_buddy_config {}
impl AutoCreate<pjsua_buddy_info> for pjsua_buddy_info {}
impl AutoCreate<pjsua_media_config> for pjsua_media_config {}
impl AutoCreate<pjsua_codec_info> for pjsua_codec_info {}
impl AutoCreate<pjsua_conf_port_info> for pjsua_conf_port_info {}
impl AutoCreate<pjsua_media_transport> for pjsua_media_transport {}
impl AutoCreate<pjsua_snd_dev_param> for pjsua_snd_dev_param {}
impl AutoCreate<pjsua_conf_connect_param> for pjsua_conf_connect_param {}
impl AutoCreate<pjsua_ext_snd_dev> for pjsua_ext_snd_dev {}
impl AutoCreate<pjsua_vid_preview_param> for pjsua_vid_preview_param {}
impl AutoCreate<pjsua_vid_win_info> for pjsua_vid_win_info {}
impl AutoCreate<pjsua_vid_conf_port_info> for pjsua_vid_conf_port_info {}