
use super::utils::AutoCreate;
use super::*;

impl AutoCreate<pjmedia_endpt> for pjmedia_endpt {}
impl AutoCreate<pjmedia_stream> for pjmedia_stream {}
impl AutoCreate<pjmedia_ratio> for pjmedia_ratio {}
impl AutoCreate<pjmedia_coord> for pjmedia_coord {}
impl AutoCreate<pjmedia_rect_size> for pjmedia_rect_size {}
impl AutoCreate<pjmedia_rect> for pjmedia_rect {}
impl AutoCreate<pjmedia_clock_src> for pjmedia_clock_src {}
impl AutoCreate<pjmedia_clock> for pjmedia_clock {}
impl AutoCreate<pjmedia_clock_param> for pjmedia_clock_param {}
impl AutoCreate<pjmedia_audio_format_detail> for pjmedia_audio_format_detail {}
impl AutoCreate<pjmedia_video_format_detail> for pjmedia_video_format_detail {}
impl AutoCreate<pjmedia_format> for pjmedia_format {}
impl AutoCreate<pjmedia_format__bindgen_ty_1> for pjmedia_format__bindgen_ty_1 {}
impl AutoCreate<pjmedia_video_apply_fmt_param> for pjmedia_video_apply_fmt_param {}
impl AutoCreate<pjmedia_video_format_info> for pjmedia_video_format_info {}
impl AutoCreate<pjmedia_video_format_mgr> for pjmedia_video_format_mgr {}
impl AutoCreate<pjmedia_frame> for pjmedia_frame {}
impl AutoCreate<pjmedia_frame_ext> for pjmedia_frame_ext {}
impl AutoCreate<pjmedia_frame_ext_subframe> for pjmedia_frame_ext_subframe {}
impl AutoCreate<pjmedia_aud_stream> for pjmedia_aud_stream {}
impl AutoCreate<pjmedia_aud_dev_factory> for pjmedia_aud_dev_factory {}
impl AutoCreate<pjmedia_aud_driver> for pjmedia_aud_driver {}
impl AutoCreate<pjmedia_aud_subsys> for pjmedia_aud_subsys {}
impl AutoCreate<pjmedia_aud_dev_info> for pjmedia_aud_dev_info {}
impl AutoCreate<pjmedia_aud_param> for pjmedia_aud_param {}
impl AutoCreate<pjmedia_rtcp_xr_rb_header> for pjmedia_rtcp_xr_rb_header {}
impl AutoCreate<pjmedia_rtcp_xr_rb_rr_time> for pjmedia_rtcp_xr_rb_rr_time {}
impl AutoCreate<pjmedia_rtcp_xr_rb_dlrr_item> for pjmedia_rtcp_xr_rb_dlrr_item {}
impl AutoCreate<pjmedia_rtcp_xr_rb_dlrr> for pjmedia_rtcp_xr_rb_dlrr {}
impl AutoCreate<pjmedia_rtcp_xr_rb_stats> for pjmedia_rtcp_xr_rb_stats {}
impl AutoCreate<pjmedia_rtcp_xr_rb_voip_mtc> for pjmedia_rtcp_xr_rb_voip_mtc {}
impl AutoCreate<pjmedia_rtcp_xr_pkt> for pjmedia_rtcp_xr_pkt {}
impl AutoCreate<pjmedia_rtcp_xr_pkt__bindgen_ty_1> for pjmedia_rtcp_xr_pkt__bindgen_ty_1 {}
impl AutoCreate<pjmedia_rtcp_xr_stream_stat> for pjmedia_rtcp_xr_stream_stat {}
impl AutoCreate<pjmedia_rtcp_xr_stream_stat__bindgen_ty_1> for pjmedia_rtcp_xr_stream_stat__bindgen_ty_1 {}
impl AutoCreate<pjmedia_rtcp_xr_stream_stat__bindgen_ty_2> for pjmedia_rtcp_xr_stream_stat__bindgen_ty_2 {}
impl AutoCreate<pjmedia_rtcp_xr_stat> for pjmedia_rtcp_xr_stat {}
impl AutoCreate<pjmedia_rtcp_xr_session> for pjmedia_rtcp_xr_session {}
impl AutoCreate<pjmedia_rtcp_xr_session__bindgen_ty_1> for pjmedia_rtcp_xr_session__bindgen_ty_1 {}
impl AutoCreate<pjmedia_rtp_hdr> for pjmedia_rtp_hdr {}
impl AutoCreate<pjmedia_rtp_ext_hdr> for pjmedia_rtp_ext_hdr {}
impl AutoCreate<pjmedia_rtp_dec_hdr> for pjmedia_rtp_dec_hdr {}
impl AutoCreate<pjmedia_rtp_dtmf_event> for pjmedia_rtp_dtmf_event {}
impl AutoCreate<pjmedia_rtp_seq_session> for pjmedia_rtp_seq_session {}
impl AutoCreate<pjmedia_rtp_session> for pjmedia_rtp_session {}
impl AutoCreate<pjmedia_rtp_status> for pjmedia_rtp_status {}
impl AutoCreate<pjmedia_rtp_status__bindgen_ty_1> for pjmedia_rtp_status__bindgen_ty_1 {}
impl AutoCreate<pjmedia_rtp_status__bindgen_ty_1_flag> for pjmedia_rtp_status__bindgen_ty_1_flag {}
impl AutoCreate<pjmedia_rtp_session_setting> for pjmedia_rtp_session_setting {}
impl AutoCreate<pjmedia_rtcp_sr> for pjmedia_rtcp_sr {}
impl AutoCreate<pjmedia_rtcp_rr> for pjmedia_rtcp_rr {}
impl AutoCreate<pjmedia_rtcp_common> for pjmedia_rtcp_common {}
impl AutoCreate<pjmedia_rtcp_sr_pkt> for pjmedia_rtcp_sr_pkt {}
impl AutoCreate<pjmedia_rtcp_rr_pkt> for pjmedia_rtcp_rr_pkt {}
impl AutoCreate<pjmedia_rtcp_sdes> for pjmedia_rtcp_sdes {}
impl AutoCreate<pjmedia_rtcp_ntp_rec> for pjmedia_rtcp_ntp_rec {}
impl AutoCreate<pjmedia_rtcp_stream_stat> for pjmedia_rtcp_stream_stat {}
impl AutoCreate<pjmedia_rtcp_stream_stat__bindgen_ty_1> for pjmedia_rtcp_stream_stat__bindgen_ty_1 {}
impl AutoCreate<pjmedia_rtcp_stat> for pjmedia_rtcp_stat {}
impl AutoCreate<pjmedia_rtcp_session> for pjmedia_rtcp_session {}
impl AutoCreate<pjmedia_rtcp_session_setting> for pjmedia_rtcp_session_setting {}
impl AutoCreate<pjmedia_sdp_attr> for pjmedia_sdp_attr {}
impl AutoCreate<pjmedia_sdp_rtpmap> for pjmedia_sdp_rtpmap {}
impl AutoCreate<pjmedia_sdp_fmtp> for pjmedia_sdp_fmtp {}
impl AutoCreate<pjmedia_sdp_rtcp_attr> for pjmedia_sdp_rtcp_attr {}
impl AutoCreate<pjmedia_sdp_ssrc_attr> for pjmedia_sdp_ssrc_attr {}
impl AutoCreate<pjmedia_sdp_conn> for pjmedia_sdp_conn {}
impl AutoCreate<pjmedia_sdp_bandw> for pjmedia_sdp_bandw {}
impl AutoCreate<pjmedia_sdp_media> for pjmedia_sdp_media {}
impl AutoCreate<pjmedia_sdp_media__bindgen_ty_1> for pjmedia_sdp_media__bindgen_ty_1 {}
impl AutoCreate<pjmedia_sdp_session> for pjmedia_sdp_session {}
impl AutoCreate<pjmedia_sdp_session__bindgen_ty_1> for pjmedia_sdp_session__bindgen_ty_1 {}
impl AutoCreate<pjmedia_sdp_session__bindgen_ty_2> for pjmedia_sdp_session__bindgen_ty_2 {}
impl AutoCreate<pjmedia_rtcp_fb_cap> for pjmedia_rtcp_fb_cap {}
impl AutoCreate<pjmedia_rtcp_fb_info> for pjmedia_rtcp_fb_info {}
impl AutoCreate<pjmedia_rtcp_fb_setting> for pjmedia_rtcp_fb_setting {}
impl AutoCreate<pjmedia_rtcp_fb_nack> for pjmedia_rtcp_fb_nack {}
impl AutoCreate<pjmedia_rtcp_fb_sli> for pjmedia_rtcp_fb_sli {}
impl AutoCreate<pjmedia_rtcp_fb_rpsi> for pjmedia_rtcp_fb_rpsi {}
impl AutoCreate<pjmedia_event_rx_rtcp_fb_data> for pjmedia_event_rx_rtcp_fb_data {}
impl AutoCreate<pjmedia_event_rx_rtcp_fb_data__bindgen_ty_1> for pjmedia_event_rx_rtcp_fb_data__bindgen_ty_1 {}
impl AutoCreate<pjmedia_vid_dev_hwnd> for pjmedia_vid_dev_hwnd {}
impl AutoCreate<pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_1> for pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_1 {}
impl AutoCreate<pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_2> for pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_2 {}
impl AutoCreate<pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_3> for pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_3 {}
impl AutoCreate<pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_4> for pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_4 {}
impl AutoCreate<pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_5> for pjmedia_vid_dev_hwnd__bindgen_ty_1__bindgen_ty_5 {}
impl AutoCreate<pjmedia_vid_dev_switch_param> for pjmedia_vid_dev_switch_param {}
impl AutoCreate<pjmedia_vid_dev_info> for pjmedia_vid_dev_info {}
impl AutoCreate<pjmedia_vid_dev_cb> for pjmedia_vid_dev_cb {}
impl AutoCreate<pjmedia_vid_dev_param> for pjmedia_vid_dev_param {}
impl AutoCreate<pjmedia_vid_driver> for pjmedia_vid_driver {}
impl AutoCreate<pjmedia_vid_subsys> for pjmedia_vid_subsys {}
impl AutoCreate<pjmedia_event_fmt_changed_data> for pjmedia_event_fmt_changed_data {}
impl AutoCreate<pjmedia_event_dummy_data> for pjmedia_event_dummy_data {}
impl AutoCreate<pjmedia_event_wnd_resized_data> for pjmedia_event_wnd_resized_data {}
impl AutoCreate<pjmedia_event_wnd_closing_data> for pjmedia_event_wnd_closing_data {}
impl AutoCreate<pjmedia_event_aud_dev_err_data> for pjmedia_event_aud_dev_err_data {}
impl AutoCreate<pjmedia_event_vid_dev_err_data> for pjmedia_event_vid_dev_err_data {}
impl AutoCreate<pjmedia_event_media_tp_err_data> for pjmedia_event_media_tp_err_data {}
impl AutoCreate<pjmedia_event> for pjmedia_event {}
impl AutoCreate<pjmedia_event__bindgen_ty_1> for pjmedia_event__bindgen_ty_1 {}
impl AutoCreate<pjmedia_event_mgr> for pjmedia_event_mgr {}
impl AutoCreate<pjmedia_port_info> for pjmedia_port_info {}
impl AutoCreate<pjmedia_port> for pjmedia_port {}
impl AutoCreate<pjmedia_port_port_data> for pjmedia_port_port_data {}
impl AutoCreate<pjmedia_avi_streams> for pjmedia_avi_streams {}
impl AutoCreate<pjmedia_circ_buf> for pjmedia_circ_buf {}
impl AutoCreate<pjmedia_codec_info> for pjmedia_codec_info {}
impl AutoCreate<pjmedia_codec_fmtp> for pjmedia_codec_fmtp {}
impl AutoCreate<pjmedia_codec_fmtp_param> for pjmedia_codec_fmtp_param {}
impl AutoCreate<pjmedia_codec_param> for pjmedia_codec_param {}
impl AutoCreate<pjmedia_codec_param__bindgen_ty_1> for pjmedia_codec_param__bindgen_ty_1 {}
impl AutoCreate<pjmedia_codec_param__bindgen_ty_2> for pjmedia_codec_param__bindgen_ty_2 {}
impl AutoCreate<pjmedia_codec_op> for pjmedia_codec_op {}
impl AutoCreate<pjmedia_codec> for pjmedia_codec {}
impl AutoCreate<pjmedia_codec_factory_op> for pjmedia_codec_factory_op {}
impl AutoCreate<pjmedia_codec_factory> for pjmedia_codec_factory {}
impl AutoCreate<pjmedia_codec_default_param> for pjmedia_codec_default_param {}
impl AutoCreate<pjmedia_codec_desc> for pjmedia_codec_desc {}
impl AutoCreate<pjmedia_codec_mgr> for pjmedia_codec_mgr {}
impl AutoCreate<pjmedia_conf> for pjmedia_conf {}
impl AutoCreate<pjmedia_conf_port_info> for pjmedia_conf_port_info {}
impl AutoCreate<pjmedia_conversion_param> for pjmedia_conversion_param {}
impl AutoCreate<pjmedia_converter_factory> for pjmedia_converter_factory {}
impl AutoCreate<pjmedia_converter> for pjmedia_converter {}
impl AutoCreate<pjmedia_converter_factory_op> for pjmedia_converter_factory_op {}
impl AutoCreate<pjmedia_converter_op> for pjmedia_converter_op {}
impl AutoCreate<pjmedia_converter_mgr> for pjmedia_converter_mgr {}
impl AutoCreate<pjmedia_delay_buf> for pjmedia_delay_buf {}
impl AutoCreate<pjmedia_echo_state> for pjmedia_echo_state {}
impl AutoCreate<pjmedia_echo_stat> for pjmedia_echo_stat {}
impl AutoCreate<pjmedia_sock_info> for pjmedia_sock_info {}
impl AutoCreate<pjmedia_transport_op> for pjmedia_transport_op {}
impl AutoCreate<pjmedia_transport> for pjmedia_transport {}
impl AutoCreate<pjmedia_transport_specific_info> for pjmedia_transport_specific_info {}
impl AutoCreate<pjmedia_transport_info> for pjmedia_transport_info {}
impl AutoCreate<pjmedia_tp_cb_param> for pjmedia_tp_cb_param {}
impl AutoCreate<pjmedia_transport_attach_param> for pjmedia_transport_attach_param {}
impl AutoCreate<pjmedia_jb_state> for pjmedia_jb_state {}
impl AutoCreate<pjmedia_jbuf> for pjmedia_jbuf {}
impl AutoCreate<pjmedia_master_port> for pjmedia_master_port {}
impl AutoCreate<pjmedia_plc> for pjmedia_plc {}
impl AutoCreate<pjmedia_resample> for pjmedia_resample {}
impl AutoCreate<pjmedia_sdp_neg> for pjmedia_sdp_neg {}
impl AutoCreate<pjmedia_silence_det> for pjmedia_silence_det {}
impl AutoCreate<pjmedia_snd_stream> for pjmedia_snd_stream {}
impl AutoCreate<pjmedia_snd_dev_info> for pjmedia_snd_dev_info {}
impl AutoCreate<pjmedia_snd_stream_info> for pjmedia_snd_stream_info {}
impl AutoCreate<pjmedia_snd_port_param> for pjmedia_snd_port_param {}
impl AutoCreate<pjmedia_snd_port> for pjmedia_snd_port {}
impl AutoCreate<pjmedia_vid_encode_opt> for pjmedia_vid_encode_opt {}
impl AutoCreate<pjmedia_vid_codec_info> for pjmedia_vid_codec_info {}
impl AutoCreate<pjmedia_vid_codec_param> for pjmedia_vid_codec_param {}
impl AutoCreate<pjmedia_vid_codec_op> for pjmedia_vid_codec_op {}
impl AutoCreate<pjmedia_vid_codec> for pjmedia_vid_codec {}
impl AutoCreate<pjmedia_vid_codec_factory_op> for pjmedia_vid_codec_factory_op {}
impl AutoCreate<pjmedia_vid_codec_factory> for pjmedia_vid_codec_factory {}
impl AutoCreate<pjmedia_vid_codec_mgr> for pjmedia_vid_codec_mgr {}
impl AutoCreate<pjmedia_stream_rtp_sess_info> for pjmedia_stream_rtp_sess_info {}
impl AutoCreate<pjmedia_channel> for pjmedia_channel {}
impl AutoCreate<pjmedia_stream_info> for pjmedia_stream_info {}
impl AutoCreate<pjmedia_stream_dtmf_event> for pjmedia_stream_dtmf_event {}
impl AutoCreate<pjmedia_tone_desc> for pjmedia_tone_desc {}
impl AutoCreate<pjmedia_tone_digit> for pjmedia_tone_digit {}
impl AutoCreate<pjmedia_tone_digit_map> for pjmedia_tone_digit_map {}
impl AutoCreate<pjmedia_tone_digit_map__bindgen_ty_1> for pjmedia_tone_digit_map__bindgen_ty_1 {}
impl AutoCreate<pjmedia_ice_cb> for pjmedia_ice_cb {}
impl AutoCreate<pjmedia_ice_transport_info> for pjmedia_ice_transport_info {}
impl AutoCreate<pjmedia_ice_transport_info__bindgen_ty_1> for pjmedia_ice_transport_info__bindgen_ty_1 {}
impl AutoCreate<pjmedia_loop_tp_setting> for pjmedia_loop_tp_setting {}
impl AutoCreate<pjmedia_srtp_crypto> for pjmedia_srtp_crypto {}
impl AutoCreate<pjmedia_srtp_cb> for pjmedia_srtp_cb {}
impl AutoCreate<pjmedia_srtp_setting> for pjmedia_srtp_setting {}
impl AutoCreate<pjmedia_srtp_info> for pjmedia_srtp_info {}
impl AutoCreate<pjmedia_srtp_dtls_nego_param> for pjmedia_srtp_dtls_nego_param {}
impl AutoCreate<pjmedia_vid_conf> for pjmedia_vid_conf {}
impl AutoCreate<pjmedia_vid_conf_setting> for pjmedia_vid_conf_setting {}
impl AutoCreate<pjmedia_vid_conf_port_info> for pjmedia_vid_conf_port_info {}
impl AutoCreate<pjmedia_vid_port_param> for pjmedia_vid_port_param {}
impl AutoCreate<pjmedia_vid_port> for pjmedia_vid_port {}
impl AutoCreate<pjmedia_vid_stream_rc_config> for pjmedia_vid_stream_rc_config {}
impl AutoCreate<pjmedia_vid_stream_sk_config> for pjmedia_vid_stream_sk_config {}
impl AutoCreate<pjmedia_vid_stream_info> for pjmedia_vid_stream_info {}
impl AutoCreate<pjmedia_vid_stream> for pjmedia_vid_stream {}
impl AutoCreate<pjmedia_wav_player_info> for pjmedia_wav_player_info {}
impl AutoCreate<pjmedia_wave_hdr> for pjmedia_wave_hdr {}
impl AutoCreate<pjmedia_wave_hdr__bindgen_ty_1> for pjmedia_wave_hdr__bindgen_ty_1 {}
impl AutoCreate<pjmedia_wave_hdr__bindgen_ty_2> for pjmedia_wave_hdr__bindgen_ty_2 {}
impl AutoCreate<pjmedia_wave_hdr__bindgen_ty_3> for pjmedia_wave_hdr__bindgen_ty_3 {}
impl AutoCreate<pjmedia_wave_subchunk> for pjmedia_wave_subchunk {}
impl AutoCreate<pjmedia_wsola> for pjmedia_wsola {}
impl AutoCreate<pjmedia_vid_dev_factory_op> for pjmedia_vid_dev_factory_op {}
impl AutoCreate<pjmedia_vid_dev_factory> for pjmedia_vid_dev_factory {}
impl AutoCreate<pjmedia_vid_dev_factory__bindgen_ty_1> for pjmedia_vid_dev_factory__bindgen_ty_1 {}
impl AutoCreate<pjmedia_vid_dev_stream_op> for pjmedia_vid_dev_stream_op {}
impl AutoCreate<pjmedia_vid_dev_stream> for pjmedia_vid_dev_stream {}
impl AutoCreate<pjmedia_vid_dev_stream__bindgen_ty_1> for pjmedia_vid_dev_stream__bindgen_ty_1 {}
impl AutoCreate<pjmedia_avi_dev_param> for pjmedia_avi_dev_param {}