use pjnath_sys::*;
use crate::prelude::AutoCreate;

impl AutoCreate<pj_stun_msg_hdr> for pj_stun_msg_hdr {}
impl AutoCreate<pj_stun_attr_hdr> for pj_stun_attr_hdr {}
impl AutoCreate<pj_stun_sockaddr_attr> for pj_stun_sockaddr_attr {}
impl AutoCreate<pj_stun_empty_attr> for pj_stun_empty_attr {}
impl AutoCreate<pj_stun_string_attr> for pj_stun_string_attr {}
impl AutoCreate<pj_stun_uint_attr> for pj_stun_uint_attr {}
impl AutoCreate<pj_stun_uint64_attr> for pj_stun_uint64_attr {}
impl AutoCreate<pj_stun_binary_attr> for pj_stun_binary_attr {}
impl AutoCreate<pj_stun_msgint_attr> for pj_stun_msgint_attr {}
impl AutoCreate<pj_stun_errcode_attr> for pj_stun_errcode_attr {}
impl AutoCreate<pj_stun_unknown_attr> for pj_stun_unknown_attr {}
impl AutoCreate<pj_stun_msg> for pj_stun_msg {}
impl AutoCreate<pj_stun_auth_cred> for pj_stun_auth_cred {}
impl AutoCreate<pj_stun_auth_cred__bindgen_ty_1> for pj_stun_auth_cred__bindgen_ty_1 {}
impl AutoCreate<pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_1> for pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_1 {}
impl AutoCreate<pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_2> for pj_stun_auth_cred__bindgen_ty_1__bindgen_ty_2 {}
impl AutoCreate<pj_stun_req_cred_info> for pj_stun_req_cred_info {}
impl AutoCreate<pj_stun_config> for pj_stun_config {}
impl AutoCreate<pj_stun_client_tsx> for pj_stun_client_tsx {}
impl AutoCreate<pj_stun_tsx_cb> for pj_stun_tsx_cb {}
impl AutoCreate<pj_stun_session> for pj_stun_session {}
impl AutoCreate<pj_stun_session_cb> for pj_stun_session_cb {}
impl AutoCreate<pj_stun_rx_data> for pj_stun_rx_data {}
impl AutoCreate<pj_stun_tx_data> for pj_stun_tx_data {}
impl AutoCreate<pj_ice_sess_comp> for pj_ice_sess_comp {}
impl AutoCreate<pj_ice_msg_data> for pj_ice_msg_data {}
impl AutoCreate<pj_ice_msg_data_data_request_data> for pj_ice_msg_data_data_request_data {}
impl AutoCreate<pj_ice_sess_cand> for pj_ice_sess_cand {}
impl AutoCreate<pj_ice_sess_check> for pj_ice_sess_check {}
impl AutoCreate<pj_ice_sess_checklist> for pj_ice_sess_checklist {}
impl AutoCreate<pj_ice_sess_cb> for pj_ice_sess_cb {}
impl AutoCreate<pj_ice_rx_check> for pj_ice_rx_check {}
impl AutoCreate<pj_ice_sess_options> for pj_ice_sess_options {}
impl AutoCreate<pj_ice_sess> for pj_ice_sess {}
impl AutoCreate<pj_stun_sock> for pj_stun_sock {}
impl AutoCreate<pj_stun_sock_cb> for pj_stun_sock_cb {}
impl AutoCreate<pj_stun_sock_info> for pj_stun_sock_info {}
impl AutoCreate<pj_stun_sock_cfg> for pj_stun_sock_cfg {}
impl AutoCreate<pj_turn_session> for pj_turn_session {}
impl AutoCreate<pj_turn_channel_data> for pj_turn_channel_data {}
impl AutoCreate<pj_turn_session_cb> for pj_turn_session_cb {}
impl AutoCreate<pj_turn_alloc_param> for pj_turn_alloc_param {}
impl AutoCreate<pj_turn_session_info> for pj_turn_session_info {}
impl AutoCreate<pj_turn_session_on_rx_pkt_param> for pj_turn_session_on_rx_pkt_param {}
impl AutoCreate<pj_turn_sock> for pj_turn_sock {}
impl AutoCreate<pj_turn_sock_cb> for pj_turn_sock_cb {}
impl AutoCreate<pj_turn_sock_tls_cfg> for pj_turn_sock_tls_cfg {}
impl AutoCreate<pj_turn_sock_cfg> for pj_turn_sock_cfg {}
impl AutoCreate<pj_ice_strans> for pj_ice_strans {}
impl AutoCreate<pj_ice_strans_cb> for pj_ice_strans_cb {}
impl AutoCreate<pj_ice_strans_stun_cfg> for pj_ice_strans_stun_cfg {}
impl AutoCreate<pj_ice_strans_turn_cfg> for pj_ice_strans_turn_cfg {}
impl AutoCreate<pj_ice_strans_cfg> for pj_ice_strans_cfg {}
impl AutoCreate<pj_ice_strans_cfg__bindgen_ty_1> for pj_ice_strans_cfg__bindgen_ty_1 {}
impl AutoCreate<pj_stun_nat_detect_result> for pj_stun_nat_detect_result {}
