// extern crate bindgen;
// use std::env;

fn main () {
    // dynamic shared library
    println!("cargo:rustc-link-lib=pj");
    println!("cargo:rustc-link-search=native=/usr/local/lib");
    println!("cargo:rerun-if-changed=wrapper.h");

    // static shared library
    // println!("cargo:rustc-link-lib=static=pj-x86_64-unknown-linux-gnu");
    // println!("cargo:rustc-link-search=native=/usr/local/lib");
    // println!("cargo:rerun-if-changed=wrapper.h");

    // generate code for lib.rs
    // generate_bindgen();
}

// fn generate_bindgen() {
//     let pj = bindgen::Builder::default().header("wrapper.h")
//     // .dynamic_library_name("pj")
//     .raw_line("#![allow(non_upper_case_globals)]")
//     .raw_line("#![allow(non_camel_case_types)]")
//     .raw_line("#![allow(non_snake_case)]")

//     .allowlist_function("ioqueue_dispatch_exception_event")
//     .allowlist_function("ioqueue_dispatch_read_event")
//     .allowlist_function("ioqueue_dispatch_write_event")
//     .allowlist_function("pj_activesock_cfg_default")
//     .allowlist_function("pj_activesock_close")
//     .allowlist_function("pj_activesock_create")
//     .allowlist_function("pj_activesock_create_udp")
//     .allowlist_function("pj_activesock_get_user_data")
//     .allowlist_function("pj_activesock_send")
//     .allowlist_function("pj_activesock_sendto")
//     .allowlist_function("pj_activesock_set_user_data")
//     .allowlist_function("pj_activesock_start_accept")
//     .allowlist_function("pj_activesock_start_connect")
//     .allowlist_function("pj_activesock_start_read")
//     .allowlist_function("pj_activesock_start_read2")
//     .allowlist_function("pj_activesock_start_recvfrom")
//     .allowlist_function("pj_activesock_start_recvfrom2")
//     .allowlist_function("pj_addr_str_print")
//     .allowlist_function("pj_array_erase")
//     .allowlist_function("pj_array_find")
//     .allowlist_function("pj_array_insert")
//     .allowlist_function("pj_atexit")
//     .allowlist_function("pj_atomic_add")
//     .allowlist_function("pj_atomic_add_and_get")
//     .allowlist_function("pj_atomic_create")
//     .allowlist_function("pj_atomic_dec")
//     .allowlist_function("pj_atomic_dec_and_get")
//     .allowlist_function("pj_atomic_destroy")
//     .allowlist_function("pj_atomic_get")
//     .allowlist_function("pj_atomic_inc")
//     .allowlist_function("pj_atomic_inc_and_get")
//     .allowlist_function("pj_atomic_set")
//     .allowlist_function("pj_caching_pool_destroy")
//     .allowlist_function("pj_caching_pool_init")
//     .allowlist_function("pj_create_random_string")
//     .allowlist_function("pj_create_unique_string")
//     .allowlist_function("pj_create_unique_string_lower")
//     .allowlist_function("pj_dump_config")
//     .allowlist_function("pj_elapsed_cycle")
//     .allowlist_function("pj_elapsed_msec")
//     .allowlist_function("pj_elapsed_msec64")
//     .allowlist_function("pj_elapsed_nanosec")
//     .allowlist_function("pj_elapsed_time")
//     .allowlist_function("pj_elapsed_usec")
//     .allowlist_function("pj_enter_critical_section")
//     .allowlist_function("pj_enum_ip_interface")
//     .allowlist_function("pj_enum_ip_interface2")
//     .allowlist_function("pj_enum_ip_route")
//     .allowlist_function("pj_errno_clear_handlers")
//     .allowlist_function("pj_event_create")
//     .allowlist_function("pj_event_destroy")
//     .allowlist_function("pj_event_pulse")
//     .allowlist_function("pj_event_reset")
//     .allowlist_function("pj_event_set")
//     .allowlist_function("pj_event_trywait")
//     .allowlist_function("pj_event_wait")
//     .allowlist_function("pj_exception_id_alloc")
//     .allowlist_function("pj_exception_id_free")
//     .allowlist_function("pj_exception_id_name")
//     .allowlist_function("PJ_FD_CLR")
//     .allowlist_function("PJ_FD_COUNT")
//     .allowlist_function("PJ_FD_ISSET")
//     .allowlist_function("PJ_FD_SET")
//     .allowlist_function("PJ_FD_ZERO")
//     .allowlist_function("pj_fifobuf_alloc")
//     .allowlist_function("pj_fifobuf_free")
//     .allowlist_function("pj_fifobuf_init")
//     .allowlist_function("pj_fifobuf_max_size")
//     .allowlist_function("pj_fifobuf_unalloc")
//     .allowlist_function("pj_file_close")
//     .allowlist_function("pj_file_delete")
//     .allowlist_function("pj_file_exists")
//     .allowlist_function("pj_file_flush")
//     .allowlist_function("pj_file_getpos")
//     .allowlist_function("pj_file_getstat")
//     .allowlist_function("pj_file_move")
//     .allowlist_function("pj_file_open")
//     .allowlist_function("pj_file_read")
//     .allowlist_function("pj_file_setpos")
//     .allowlist_function("pj_file_size")
//     .allowlist_function("pj_file_write")
//     .allowlist_function("pj_generate_unique_string")
//     .allowlist_function("pj_generate_unique_string_lower")
//     .allowlist_function("pj_getaddrinfo")
//     .allowlist_function("pj_getdefaultipinterface")
//     .allowlist_function("pj_gethostaddr")
//     .allowlist_function("pj_gethostbyname")
//     .allowlist_function("pj_gethostip")
//     .allowlist_function("pj_gethostname")
//     .allowlist_function("pj_getipinterface")
//     .allowlist_function("pj_get_netos_error")
//     .allowlist_function("pj_get_os_error")
//     .allowlist_function("pj_getpid")
//     .allowlist_function("pj_get_sys_info")
//     .allowlist_function("pj_gettickcount")
//     .allowlist_function("pj_gettimeofday")
//     .allowlist_function("pj_get_timestamp")
//     .allowlist_function("pj_get_timestamp_freq")
//     .allowlist_function("pj_get_version")
//     .allowlist_function("pj_grp_lock_acquire")
//     .allowlist_function("pj_grp_lock_add_handler")
//     .allowlist_function("pj_grp_lock_add_ref")
//     .allowlist_function("pj_grp_lock_chain_lock")
//     .allowlist_function("pj_grp_lock_config_default")
//     .allowlist_function("pj_grp_lock_create")
//     .allowlist_function("pj_grp_lock_create_w_handler")
//     .allowlist_function("pj_grp_lock_dec_ref")
//     .allowlist_function("pj_grp_lock_del_handler")
//     .allowlist_function("pj_grp_lock_destroy")
//     .allowlist_function("pj_grp_lock_dump")
//     .allowlist_function("pj_grp_lock_get_ref")
//     .allowlist_function("pj_grp_lock_release")
//     .allowlist_function("pj_grp_lock_replace")
//     .allowlist_function("pj_grp_lock_tryacquire")
//     .allowlist_function("pj_grp_lock_unchain_lock")
//     .allowlist_function("pj_GUID_STRING_LENGTH")
//     .allowlist_function("pj_hash_calc")
//     .allowlist_function("pj_hash_calc_tolower")
//     .allowlist_function("pj_hash_count")
//     .allowlist_function("pj_hash_create")
//     .allowlist_function("pj_hash_first")
//     .allowlist_function("pj_hash_get")
//     .allowlist_function("pj_hash_get_lower")
//     .allowlist_function("pj_hash_next")
//     .allowlist_function("pj_hash_set")
//     .allowlist_function("pj_hash_set_lower")
//     .allowlist_function("pj_hash_set_np")
//     .allowlist_function("pj_hash_set_np_lower")
//     .allowlist_function("pj_hash_this")
//     .allowlist_function("pj_htonl")
//     .allowlist_function("pj_htons")
//     .allowlist_function("pj_inet_addr")
//     .allowlist_function("pj_inet_addr2")
//     .allowlist_function("pj_inet_aton")
//     .allowlist_function("pj_inet_ntoa")
//     .allowlist_function("pj_inet_ntop")
//     .allowlist_function("pj_inet_ntop2")
//     .allowlist_function("pj_inet_pton")
//     .allowlist_function("pj_init")

//     .allowlist_function("pj_ioqueue_accept")
//     .allowlist_function("pj_ioqueue_connect")
//     .allowlist_function("pj_ioqueue_create")
//     .allowlist_function("pj_ioqueue_destroy")
//     .allowlist_function("pj_ioqueue_get_user_data")
//     .allowlist_function("pj_ioqueue_is_pending")
//     .allowlist_function("pj_ioqueue_lock_key")
//     .allowlist_function("pj_ioqueue_name")
//     .allowlist_function("pj_ioqueue_op_key_init")
//     .allowlist_function("pj_ioqueue_poll")
//     .allowlist_function("pj_ioqueue_post_completion")
//     .allowlist_function("pj_ioqueue_recv")
//     .allowlist_function("pj_ioqueue_recvfrom")
//     .allowlist_function("pj_ioqueue_register_sock")
//     .allowlist_function("pj_ioqueue_register_sock2")
//     .allowlist_function("pj_ioqueue_send")
//     .allowlist_function("pj_ioqueue_sendto")
//     .allowlist_function("pj_ioqueue_set_concurrency")
//     .allowlist_function("pj_ioqueue_set_default_concurrency")
//     .allowlist_function("pj_ioqueue_set_lock")
//     .allowlist_function("pj_ioqueue_set_user_data")
//     .allowlist_function("pj_ioqueue_trylock_key")
//     .allowlist_function("pj_ioqueue_unlock_key")
//     .allowlist_function("pj_ioqueue_unregister")

//     .allowlist_function("pj_leave_critical_section")

//     .allowlist_function("pj_list_erase")
//     .allowlist_function("pj_list_find_node")
//     .allowlist_function("pj_list_insert_after")
//     .allowlist_function("pj_list_insert_before")
//     .allowlist_function("pj_list_insert_nodes_after")
//     .allowlist_function("pj_list_insert_nodes_before")
//     .allowlist_function("pj_list_merge_first")
//     .allowlist_function("pj_list_merge_last")
//     .allowlist_function("pj_list_search")
//     .allowlist_function("pj_list_size")

//     .allowlist_function("pj_lock_acquire")
//     .allowlist_function("pj_lock_create_null_mutex")
//     .allowlist_function("pj_lock_create_recursive_mutex")
//     .allowlist_function("pj_lock_create_semaphore")
//     .allowlist_function("pj_lock_create_simple_mutex")
//     .allowlist_function("pj_lock_destroy")
//     .allowlist_function("pj_lock_release")
//     .allowlist_function("pj_lock_tryacquire")

//     .allowlist_function("pj_log")
//     .allowlist_function("pj_log_1")
//     .allowlist_function("pj_log_2")
//     .allowlist_function("pj_log_3")
//     .allowlist_function("pj_log_4")
//     .allowlist_function("pj_log_5")
//     .allowlist_function("pj_log_add_indent")
//     .allowlist_function("pj_log_get_color")
//     .allowlist_function("pj_log_get_decor")
//     .allowlist_function("pj_log_get_level")
//     .allowlist_function("pj_log_get_log_func")
//     .allowlist_function("pj_log_init")
//     .allowlist_function("pj_log_pop_indent")
//     .allowlist_function("pj_log_push_indent")
//     .allowlist_function("pj_log_set_color")
//     .allowlist_function("pj_log_set_decor")
//     .allowlist_function("pj_log_set_level")
//     .allowlist_function("pj_log_set_log_func")
//     .allowlist_function("pj_log_write")

//     .allowlist_function("pj_mutex_create")
//     .allowlist_function("pj_mutex_create_recursive")
//     .allowlist_function("pj_mutex_create_simple")
//     .allowlist_function("pj_mutex_destroy")
//     .allowlist_function("pj_mutex_is_locked")
//     .allowlist_function("pj_mutex_lock")
//     .allowlist_function("pj_mutex_trylock")
//     .allowlist_function("pj_mutex_unlock")

//     .allowlist_function("pj_NO_MEMORY_EXCEPTION")
//     .allowlist_function("pj_ntohl")
//     .allowlist_function("pj_ntohs")

//     .allowlist_function("pj_perror")
//     .allowlist_function("pj_perror_1")
//     .allowlist_function("pj_perror_2")
//     .allowlist_function("pj_perror_3")
//     .allowlist_function("pj_perror_4")
//     .allowlist_function("pj_perror_5")

//     .allowlist_function("pj_pool_alloc")
//     .allowlist_function("pj_pool_allocate_find")
//     .allowlist_function("pj_pool_alloc_from_block")
//     .allowlist_function("pj_pool_calloc")
//     .allowlist_function("pj_pool_create")
//     .allowlist_function("pj_pool_create_int")
//     .allowlist_function("pj_pool_create_on_buf")
//     .allowlist_function("pj_pool_destroy_int")
//     .allowlist_function("pj_pool_factory_get_default_policy")
//     .allowlist_function("pj_pool_get_capacity")
//     .allowlist_function("pj_pool_getobjname")
//     .allowlist_function("pj_pool_get_used_size")
//     .allowlist_function("pj_pool_init_int")
//     .allowlist_function("pj_pool_release")
//     .allowlist_function("pj_pool_reset")
//     .allowlist_function("pj_pool_safe_release")
//     .allowlist_function("pj_pool_secure_release")

//     .allowlist_function("pj_pop_exception_handler_")

//     .allowlist_function("pj_push_exception_handler_")

//     .allowlist_function("pj_qos_get_params")
//     .allowlist_function("pj_qos_get_type")

//     .allowlist_function("pj_rand")

//     .allowlist_function("pj_rbtree_erase")
//     .allowlist_function("pj_rbtree_find")
//     .allowlist_function("pj_rbtree_first")
//     .allowlist_function("pj_rbtree_init")
//     .allowlist_function("pj_rbtree_insert")
//     .allowlist_function("pj_rbtree_last")
//     .allowlist_function("pj_rbtree_max_height")
//     .allowlist_function("pj_rbtree_min_height")
//     .allowlist_function("pj_rbtree_next")
//     .allowlist_function("pj_rbtree_prev")

//     .allowlist_function("pj_register_strerror")
//     .allowlist_function("pj_run_app")

//     .allowlist_function("pj_rwmutex_create")
//     .allowlist_function("pj_rwmutex_destroy")
//     .allowlist_function("pj_rwmutex_lock_read")
//     .allowlist_function("pj_rwmutex_lock_write")
//     .allowlist_function("pj_rwmutex_unlock_read")
//     .allowlist_function("pj_rwmutex_unlock_write")

//     .allowlist_function("pj_sem_create")
//     .allowlist_function("pj_sem_destroy")
//     .allowlist_function("pj_sem_post")
//     .allowlist_function("pj_sem_trywait")
//     .allowlist_function("pj_sem_wait")

//     .allowlist_function("pj_set_netos_error")
//     .allowlist_function("pj_set_os_error")
//     .allowlist_function("pj_shutdown")
//     .allowlist_function("pj_sock_accept")

//     .allowlist_function("pj_sockaddr_cmp")
//     .allowlist_function("pj_sockaddr_copy_addr")
//     .allowlist_function("pj_sockaddr_cp")
//     .allowlist_function("pj_sockaddr_get_addr")
//     .allowlist_function("pj_sockaddr_get_addr_len")
//     .allowlist_function("pj_sockaddr_get_len")
//     .allowlist_function("pj_sockaddr_get_port")
//     .allowlist_function("pj_sockaddr_has_addr")
//     .allowlist_function("pj_sockaddr_in_get_addr")
//     .allowlist_function("pj_sockaddr_in_get_port")
//     .allowlist_function("pj_sockaddr_in_init")
//     .allowlist_function("pj_sockaddr_init")
//     .allowlist_function("pj_sockaddr_in_set_addr")
//     .allowlist_function("pj_sockaddr_in_set_port")
//     .allowlist_function("pj_sockaddr_in_set_str_addr")
//     .allowlist_function("pj_sockaddr_parse")
//     .allowlist_function("pj_sockaddr_parse2")
//     .allowlist_function("pj_sockaddr_print")
//     .allowlist_function("pj_sockaddr_set_port")
//     .allowlist_function("pj_sockaddr_set_str_addr")
//     .allowlist_function("pj_sockaddr_synthesize")
//     .allowlist_function("pj_sock_apply_qos")
//     .allowlist_function("pj_sock_apply_qos2")
//     .allowlist_function("pj_sock_bind")
//     .allowlist_function("pj_sock_bind_in")
//     .allowlist_function("pj_sock_bind_random")
//     .allowlist_function("pj_sock_close")
//     .allowlist_function("pj_sock_connect")
//     .allowlist_function("pj_sock_getpeername")
//     .allowlist_function("pj_sock_get_qos_params")
//     .allowlist_function("pj_sock_get_qos_type")
//     .allowlist_function("pj_sock_getsockname")
//     .allowlist_function("pj_sock_getsockopt")
//     .allowlist_function("pj_sock_listen")
//     .allowlist_function("pj_sock_recv")
//     .allowlist_function("pj_sock_recvfrom")
//     .allowlist_function("pj_sock_select")
//     .allowlist_function("pj_sock_send")
//     .allowlist_function("pj_sock_sendto")
//     .allowlist_function("pj_sock_set_qos_params")
//     .allowlist_function("pj_sock_set_qos_type")
//     .allowlist_function("pj_sock_setsockopt")
//     .allowlist_function("pj_sock_setsockopt_params")
//     .allowlist_function("pj_sock_setsockopt_sobuf")
//     .allowlist_function("pj_sock_shutdown")
//     .allowlist_function("pj_sock_socket")

//     .allowlist_function("pj_srand")

//     .allowlist_function("pj_ssl_cert_get_verify_status_strings")
//     .allowlist_function("pj_ssl_cert_info_dump")
//     .allowlist_function("pj_ssl_cert_load_from_buffer")
//     .allowlist_function("pj_ssl_cert_load_from_files")
//     .allowlist_function("pj_ssl_cert_load_from_files2")
//     .allowlist_function("pj_ssl_cert_wipe_keys")
//     .allowlist_function("pj_ssl_cipher_get_availables")
//     .allowlist_function("pj_ssl_cipher_id")
//     .allowlist_function("pj_ssl_cipher_is_supported")
//     .allowlist_function("pj_ssl_cipher_name")
//     .allowlist_function("pj_ssl_curve_get_availables")
//     .allowlist_function("pj_ssl_curve_id")
//     .allowlist_function("pj_ssl_curve_is_supported")
//     .allowlist_function("pj_ssl_curve_name")
//     .allowlist_function("pj_ssl_sock_close")
//     .allowlist_function("pj_ssl_sock_create")
//     .allowlist_function("pj_ssl_sock_get_info")
//     .allowlist_function("pj_ssl_sock_get_user_data")
//     .allowlist_function("pj_ssl_sock_param_copy")
//     .allowlist_function("pj_ssl_sock_param_default")
//     .allowlist_function("pj_ssl_sock_renegotiate")
//     .allowlist_function("pj_ssl_sock_send")
//     .allowlist_function("pj_ssl_sock_sendto")
//     .allowlist_function("pj_ssl_sock_set_certificate")
//     .allowlist_function("pj_ssl_sock_set_user_data")
//     .allowlist_function("pj_ssl_sock_start_accept")
//     .allowlist_function("pj_ssl_sock_start_accept2")
//     .allowlist_function("pj_ssl_sock_start_connect")
//     .allowlist_function("pj_ssl_sock_start_connect2")
//     .allowlist_function("pj_ssl_sock_start_read")
//     .allowlist_function("pj_ssl_sock_start_read2")
//     .allowlist_function("pj_ssl_sock_start_recvfrom")
//     .allowlist_function("pj_ssl_sock_start_recvfrom2")

//     .allowlist_function("pj_str")
//     .allowlist_function("pj_strassign")
//     .allowlist_function("pj_strcat")
//     .allowlist_function("pj_strcat2")
//     .allowlist_function("pj_strcmp")
//     .allowlist_function("pj_strcmp2")
//     .allowlist_function("pj_strcpy")
//     .allowlist_function("pj_strcpy2")
//     .allowlist_function("pj_strcspn")
//     .allowlist_function("pj_strcspn2")
//     .allowlist_function("pj_strdup")
//     .allowlist_function("pj_strdup2")
//     .allowlist_function("pj_strdup2_with_null")
//     .allowlist_function("pj_strdup3")
//     .allowlist_function("pj_strdup_with_null")
//     .allowlist_function("pj_strerror")
//     .allowlist_function("pj_stricmp")
//     .allowlist_function("pj_stricmp2")
//     .allowlist_function("pj_stristr")
//     .allowlist_function("pj_strltrim")
//     .allowlist_function("pj_strncmp")
//     .allowlist_function("pj_strncmp2")
//     .allowlist_function("pj_strncpy")
//     .allowlist_function("pj_strncpy_with_null")
//     .allowlist_function("pj_strnicmp")
//     .allowlist_function("pj_strnicmp2")
//     .allowlist_function("pj_strrtrim")
//     .allowlist_function("pj_strspn")
//     .allowlist_function("pj_strspn2")
//     .allowlist_function("pj_strstr")
//     .allowlist_function("pj_strtof")
//     .allowlist_function("pj_strtok")
//     .allowlist_function("pj_strtok2")
//     .allowlist_function("pj_strtol")
//     .allowlist_function("pj_strtol2")
//     .allowlist_function("pj_strtoul")
//     .allowlist_function("pj_strtoul2")
//     .allowlist_function("pj_strtoul3")
//     .allowlist_function("pj_strtrim")

//     .allowlist_function("pj_term_get_color")
//     .allowlist_function("pj_term_set_color")

//     .allowlist_function("pj_thread_create")
//     .allowlist_function("pj_thread_destroy")
//     .allowlist_function("pj_thread_get_name")
//     .allowlist_function("pj_thread_get_os_handle")
//     .allowlist_function("pj_thread_get_prio")
//     .allowlist_function("pj_thread_get_prio_max")
//     .allowlist_function("pj_thread_get_prio_min")
//     .allowlist_function("pj_thread_init")
//     .allowlist_function("pj_thread_is_registered")
//     .allowlist_function("pj_thread_join")
//     .allowlist_function("pj_thread_local_alloc")
//     .allowlist_function("pj_thread_local_free")
//     .allowlist_function("pj_thread_local_get")
//     .allowlist_function("pj_thread_local_set")
//     .allowlist_function("pj_thread_register")
//     .allowlist_function("pj_thread_resume")
//     .allowlist_function("pj_thread_set_prio")
//     .allowlist_function("pj_thread_sleep")
//     .allowlist_function("pj_thread_this")

//     .allowlist_function("pj_throw_exception_")

//     .allowlist_function("pj_time_decode")
//     .allowlist_function("pj_time_encode")
//     .allowlist_function("pj_time_gmt_to_local")
//     .allowlist_function("pj_time_local_to_gmt")

//     .allowlist_function("pj_timer_entry_init")
//     .allowlist_function("pj_timer_entry_running")
//     .allowlist_function("pj_timer_heap_cancel")
//     .allowlist_function("pj_timer_heap_cancel_if_active")
//     .allowlist_function("pj_timer_heap_count")
//     .allowlist_function("pj_timer_heap_create")
//     .allowlist_function("pj_timer_heap_destroy")
//     .allowlist_function("pj_timer_heap_dump")
//     .allowlist_function("pj_timer_heap_earliest_time")
//     .allowlist_function("pj_timer_heap_mem_size")
//     .allowlist_function("pj_timer_heap_poll")
//     .allowlist_function("pj_timer_heap_schedule_dbg")
//     .allowlist_function("pj_timer_heap_schedule_w_grp_lock_dbg")
//     .allowlist_function("pj_timer_heap_set_lock")
//     .allowlist_function("pj_timer_heap_set_max_timed_out_per_poll")
//     .allowlist_function("pj_time_val_normalize")

//     .allowlist_function("pj_utoa")
//     .allowlist_function("pj_utoa_pad")
//     .allowlist_function("platform_strerror")

//     .allowlist_var("PJ_AF_INET")
//     .allowlist_var("PJ_AF_INET6")
//     .allowlist_var("PJ_AF_IRDA")
//     .allowlist_var("PJ_AF_PACKET")
//     .allowlist_var("PJ_AF_UNIX")
//     .allowlist_var("PJ_AF_UNSPEC")
//     .allowlist_var("PJ_GUID_STRING_LENGTH")
//     .allowlist_var("PJ_IP_ADD_MEMBERSHIP")
//     .allowlist_var("PJ_IP_DROP_MEMBERSHIP")
//     .allowlist_var("PJ_IP_MULTICAST_IF")
//     .allowlist_var("PJ_IP_MULTICAST_LOOP")
//     .allowlist_var("PJ_IP_MULTICAST_TTL")
//     .allowlist_var("PJ_IP_TOS")
//     .allowlist_var("PJ_IPTOS_LOWDELAY")
//     .allowlist_var("PJ_IPTOS_MINCOST")
//     .allowlist_var("PJ_IPTOS_RELIABILITY")
//     .allowlist_var("PJ_IPTOS_THROUGHPUT")
//     .allowlist_var("PJ_IPV6_TCLASS")
//     .allowlist_var("PJ_MSG_DONTROUTE")
//     .allowlist_var("PJ_MSG_OOB")
//     .allowlist_var("PJ_MSG_PEEK")
//     .allowlist_var("PJ_SOCK_DGRAM")
//     .allowlist_var("PJ_SOCK_RAW")
//     .allowlist_var("PJ_SOCK_RDM")
//     .allowlist_var("PJ_SOCK_STREAM")
//     .allowlist_var("PJ_SOL_IP")
//     .allowlist_var("PJ_SOL_IPV6")
//     .allowlist_var("PJ_SOL_SOCKET")
//     .allowlist_var("PJ_SOL_TCP")
//     .allowlist_var("PJ_SOL_UDP")
//     .allowlist_var("PJ_SO_NOSIGPIPE")
//     .allowlist_var("PJ_SO_PRIORITY")
//     .allowlist_var("PJ_SO_RCVBUF")
//     .allowlist_var("PJ_SO_REUSEADDR")
//     .allowlist_var("PJ_SO_SNDBUF")
//     .allowlist_var("PJ_SO_TYPE")
//     .allowlist_var("PJ_TCP_NODELAY")

//     .allowlist_var("pj_pool_factory_default_policy")
//     .allowlist_var("PJ_VERSION")

//     .allowlist_type("PJ.*")
//     .allowlist_type("pj.*")
//     .allowlist_var("pj.*")
//     .allowlist_var("PJ.*")

//     .allowlist_recursively(true)
//     .translate_enum_integer_types(true)
//     .layout_tests(false)
//     .prepend_enum_name(false)
//     .impl_debug(true)
//     .generate()
//     // Unwrap the Result and panic on failure.
//     .expect("Unable to generate bindings");

//     // Write the bindings to the $OUT_DIR/bindings.rs file.
//     // let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
//     let out_path = env::current_dir().unwrap();
//     pj.write_to_file(out_path.join("src/lib.rs")).expect("Error write src/lib.rs");
// }
