[package]
name = "pj-sys"
version = "0.1.0"
authors = ["tamara"]
edition = "2018"
build = "build.rs"

[lib]
name = "pj_sys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
# bindgen = "0.58.1"
